/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graficos;

import TorresDeHanoi.Disco;
import TorresDeHanoi.Juego;
import TorresDeHanoi.Mapa;
import TorresDeHanoi.Torre;
import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Stack;

/**
 *
 * @author Leonardo
 */
public class GeneradorPasos extends javax.swing.JFrame {

    private Juego j;
    private Stack st;
    private boolean paint = false;
    private boolean bckpaint=false;
    
    /**
     * Creates new form GeneradorPasos
     */
    public GeneradorPasos(int ndiscos, int niveli) {
        initComponents();
        j = new Juego(ndiscos, niveli, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1next.setText("Siguiente");
        jButton1next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1next)
                .addContainerGap(313, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addComponent(jButton1next)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1nextActionPerformed
        // TODO add your handling code here:
        
        j.MotorJuegoPasitos();
        paint = true;
        this.repaint();
        st = j.getSt();
    }//GEN-LAST:event_jButton1nextActionPerformed

    @Override
    public void paint(Graphics g) {
        g.setColor(new Color(255, 255, 255));
        g.fillRect(0, 0, 880, 880);
        g.setColor(new Color(0, 0, 0));
        g.fillRect(20, 260, 100, 10);//Torre 1 base
        g.fillRect(140, 260, 100, 10);//Torre 2 base
        g.fillRect(260, 260, 100, 10);//Torre 3 base
        g.fillRect(65, 70, 10, 200);//Torre 1 pilar
        g.fillRect(185, 70, 10, 200);//Torre 2 pilar
        g.fillRect(305, 70, 10, 200);//Torre 3 pilar
        g.setColor(new Color(255, 0, 0));
        ArrayList discos;
        Disco aux;
        int tam;
        int xaux;
        int x;
        int y=260;
        if(this.bckpaint==true){
            g.setColor(new Color(0, 153, 51));
        }
        if (paint == true) {
            Mapa m = (Mapa) st.pop();
            Torre[] t1 = m.getT();
            discos = t1[0].getTorre();
            for (int k = 0; k < t1[0].getTorre().size(); k++) {
                aux = (Disco) discos.get(k);
                tam = aux.getTamaño();
                x=20+(tam*10);
                xaux=65;
                y=y-20;
                g.fillRect(xaux, y, x, 10);
                g.fillRect(xaux-(x-10), y, x, 10);
            }
            
            y=260;
            discos = t1[1].getTorre();
            for (int k = 0; k < t1[1].getTorre().size(); k++) {
                aux = (Disco) discos.get(k);
                tam = aux.getTamaño();
                
                x=20+(tam*10);
                xaux=185;
                y=y-20;
                g.fillRect(xaux, y, x, 10);
                g.fillRect(xaux-(x-10), y, x, 10);
            }
            
            y=260;
            discos = t1[2].getTorre();
            for (int k = 0; k < t1[2].getTorre().size(); k++) {
                aux = (Disco) discos.get(k);
                tam = aux.getTamaño();
                
                x=20+(tam*10);
                xaux=305;
                y=y-20;
                g.fillRect(xaux, y, x, 10);
                g.fillRect(xaux-(x-10), y, x, 10);
            }
            this.bckpaint=false;
        }   
    }

    public void setBckpaint(boolean bckpaint) {
        this.bckpaint = bckpaint;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1next;
    // End of variables declaration//GEN-END:variables
}
